# Generated by Django 3.0.11 on 2022-01-10 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220109_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlibrary',
            options={'verbose_name_plural': 'User Libraries'},
        ),
    ]
